In [ ]:
import numpy as np
marks=np.array([[78,85,90],
                  [45,60,55],
                  [88,92,95],
                  [30,40,35],
                  [65,70,75]])
print("matrix shape:-")
print(marks.shape)
print("number of elements:-")
print(marks.size)
print("matrix array datatype:-")
print(marks.dtype)
print("student2 all subject marks:-")
print(marks[1:2])
print("subject3 marks of all students:-")
print(marks[:,2])
print("student1 subject 1:- ",marks[:1,1:2])
sum=np.sum(marks,axis=1)
subject=np.sum(marks,axis=0)
sum//=3
subject//=5
print("avergae greater than 80 students:-")
print(np.where(sum>=80,sum,0))
print("grace marks:-")
print(marks+5)
print("pass/fail mappping:-")
print(np.where(marks>49,1,0))
avg = np.average(marks,axis=1)
print("grades allocation")
print(np.where(avg>84,"Score:10",np.where(avg>69,"Score: 8",np.where(avg>49,"Score 6","Score :0"))))
backup=marks
backup1=marks.copy()
marks[0,0]=0
print("checking the copy vs view:-")
print("assignment:-")
print(backup)
print("copy function array:-")
print(backup1)

matrix shape:-
(5, 3)
number of elements:-
15
matrix array datatype:-
int64
student2 all subject marks:-
[[45 60 55]]
subject3 marks of all students:-
[90 55 95 35 75]
student1 subject 1:-  [[85]]
avergae greater than 80 students:-
[84  0 91  0  0]
grace marks:-
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]
pass/fail mappping:-
[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]
grades allocation
['Score:10' 'Score 6' 'Score:10' 'Score :0' 'Score: 8']
checking the copy vs view:-
assignment:-
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
copy function array:-
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
import numpy as np
electricity=np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)
print(electricity.dtype)
print(electricity.ndim)
print(np.average(electricity,axis=1))
avg=np.average(electricity,axis=1)
print(np.argmax(electricity,axis=1))
print(np.argmax(avg))
print(np.sum(electricity,axis=1))
sum=np.sum(electricity,axis=1)
print(np.argmax(electricity))
newarray=np.where(electricity>550,electricity*1.20,electricity)
print(newarray)
m=np.mean(electricity,axis=1)
print(m)
print(np.where(electricity>m[0],"true","false"))
reshaped=electricity.reshape(1,28)
print(reshaped)
print(reshaped.reshape(2,14))
ref_backup=electricity
safe_backup=electricity.copy()
electricity[2,4]=0
print(ref_backup)
print(safe_backup)

[[511 431 592 560 365 525 131]
 [126 550 425 393 166 476 420]
 [171 562 190 151 242 359 335]
 [552 277 307 333 348 423 164]]
(4, 7)
28
int64
2
[445.         365.14285714 287.14285714 343.42857143]
[2 1 1 0]
0
[3115 2556 2010 2404]
2
[[511.  431.  710.4 672.  365.  525.  131. ]
 [126.  550.  425.  393.  166.  476.  420. ]
 [171.  674.4 190.  151.  242.  359.  335. ]
 [662.4 277.  307.  333.  348.  423.  164. ]]
[445.         365.14285714 287.14285714 343.42857143]
[['true' 'false' 'true' 'true' 'false' 'true' 'false']
 ['false' 'true' 'false' 'false' 'false' 'true' 'false']
 ['false' 'true' 'false' 'false' 'false' 'false' 'false']
 ['true' 'false' 'false' 'false' 'false' 'false' 'false']]
[[511 431 592 560 365 525 131 126 550 425 393 166 476 420 171 562 190 151
  242 359 335 552 277 307 333 348 423 164]]
[[511 431 592 560 365 525 131 126 550 425 393 166 476 420]
 [171 562 190 151 242 359 335 552 277 307 333 348 423 164]]
[[511 431 592 560 365 525 131]
 [126 550 425 393 166 476 420]
 [17