In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[1:2,1:2])

[[5]]


In [ ]:
import numpy as np
#arange is a function which gives the array with start index and upto end into the function
np.arange(5,51,5)
#5 means start of the array and 51 is the end it should be plus one of the ending we need and last is the step no of increment for the start

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
import numpy as np
a=np.ones((2,2))
print(a.ndim)
#filling the array with element in function
np.full((2,2),10)
#2 means row and colmun and 10 is the element

2


array([[10, 10],
       [10, 10]])

In [ ]:
import numpy as np
#these functions give us radnom numbers between the start and end and size is matrix which gives 2x3 and int at last is type of numbers we need
a=np.random.randint(2,100,size=(2,3))
#returns the max element index in the array
np.argmax(a)
#minelemnt
np.argmax(a)

np.int64(3)

In [ ]:
import numpy as np
#gives the evenly spaced array in between elements provided at last in the function
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
import numpy as py
import pandas as pd
df=pd.read_csv("test.csv")
df.tail()
df.info()
df.columns
df.describe().T
df.describe(include="object").T
num_col=df.select_dtypes(include=["int64","float64"])
df.isnull().sum()
#

In [ ]:
#founndations of used for multiplication
np.dot()

In [ ]:
#2d array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
#creating a array with zeroes with float as a data type
np.zeros(4)
#create a matrix with it
np.zeros((3,3))


[[1 2 3]
 [4 5 6]]


In [ ]:
#expilict type conversion
arr=np.array([1.2,3.4,5.6])
arr_int= arr.astype(int)
print(arr_int)
#indexing and slicing
print(arr_int[-1])
print(arr_int[::])
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
#copying the one array into another
print(a[1::,1:2:])
b=arr_int.copy()
print(b)
print(b*a)
#universal functions
np.sqrt(a)
np.log(a)
np.exp(a)
np.max(a)
np.min(a)
np.mean(a)
np.sum(a)
np.std(a)#standard devation
#boolean  indexing print the elements which satisfy the conditions
print(a[a>1])
#here print only satisfy or not like zero or ones
print(a>1)
#broadcasting rules
print(a+10)
#reshaping arrays
e=np.arange(12)
print(e)

[1 3 5]
5
[1 3 5]
2
[[5]]
[1 3 5]
[[ 1  6 15]
 [ 4 15 30]]
[2 3 4 5 6]
[[False  True  True]
 [ True  True  True]]
[[11 12 13]
 [14 15 16]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
import numpy as np
price=np.array([1500,3000,5000])
sales=np.array([[10,15,8,12],
                [5,7,4,6],
                [2,3,2,4]])
print(price.shape)
print(price.ndim)
print(sales.shape)
print(sales.ndim)
sales+2
#print(np.dot(price,sales))
print(np.sqrt(sales))
print("sales of smartphone")
print(sales[0:1])
print("sales of all products mon to tues:-")
print(sales[:][0:2])
print("speaker sales on thursday:-",sales[1,3])
print("sales of headphones and smartphones for monday to tuesday:-")
print(sales[1:,0:2])
print(sales.reshape(1,12))
print(sales.reshape(2,6))
print(np.linspace(0,100,10))
print(np.random.randint(0,20,size=(3,4)))
print(np.random.rand(5))
print("sales total:-",sales.sum())
print("sales total row wise:-",sales.sum(axis=1))

(3,)
1
(3, 4)
2
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]
sales of smartphone
[[10 15  8 12]]
sales of all products mon to tues:-
[[10 15  8 12]
 [ 5  7  4  6]]
speaker sales on thursday:- 6
sales of headphones and smartphones for monday to tuesday:-
[[5 7]
 [2 3]]
[[10 15  8 12  5  7  4  6  2  3  2  4]]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[[ 5  1  5  8]
 [16 18 16  6]
 [ 2  1 15 17]]
[0.73952386 0.99452365 0.22599726 0.45060351 0.96463878]
sales total:- 78
sales total row wise:- [45 22 11]


In [ ]:
#axis in numpy
temp=np.array([[1,2,3],
           [4,5,6]])
print(np.sum(temp,axis=0))#colmuns
print(np.sum(temp,axis=1))#rows
#where in numpy
print(np.where(temp<3,0,temp))

[5 7 9]
[ 6 15]
[[0 0 3]
 [4 5 6]]
